# Generated by Django 5.1.3 on 2025-04-20 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='pricing',
            field=models.CharField(choices=[('Free', 'Free'), ('Freemium', 'Freemium'), ('Paid', 'Paid'), ('Subscription', 'Subscription')], default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='tool',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the tool', max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
